//import javafx.scene.paint.Color;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 90553
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        faturabilgisi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rapor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kontrol = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ilaç = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hasta = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kapat1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("TERAPİSTİM");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Klinik Sistemi");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        faturabilgisi.setBackground(new java.awt.Color(255, 255, 255));
        faturabilgisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        faturabilgisi.setForeground(new java.awt.Color(204, 204, 255));
        faturabilgisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faturabilgisiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faturabilgisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faturabilgisiMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kazanç2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Gelir Yöentim");

        javax.swing.GroupLayout faturabilgisiLayout = new javax.swing.GroupLayout(faturabilgisi);
        faturabilgisi.setLayout(faturabilgisiLayout);
        faturabilgisiLayout.setHorizontalGroup(
            faturabilgisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faturabilgisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faturabilgisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        faturabilgisiLayout.setVerticalGroup(
            faturabilgisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faturabilgisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rapor.setBackground(new java.awt.Color(255, 255, 255));
        rapor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        rapor.setForeground(new java.awt.Color(204, 204, 255));
        rapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raporMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raporMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Rapor");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rapor.png"))); // NOI18N

        javax.swing.GroupLayout raporLayout = new javax.swing.GroupLayout(rapor);
        rapor.setLayout(raporLayout);
        raporLayout.setHorizontalGroup(
            raporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, raporLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(raporLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        raporLayout.setVerticalGroup(
            raporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raporLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kontrol.setBackground(new java.awt.Color(255, 255, 255));
        kontrol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        kontrol.setForeground(new java.awt.Color(204, 204, 255));
        kontrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kontrolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kontrolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kontrolMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Seans Bilgileri ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kontrol2.png"))); // NOI18N

        javax.swing.GroupLayout kontrolLayout = new javax.swing.GroupLayout(kontrol);
        kontrol.setLayout(kontrolLayout);
        kontrolLayout.setHorizontalGroup(
            kontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontrolLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kontrolLayout.setVerticalGroup(
            kontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kontrolLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ilaç.setBackground(new java.awt.Color(255, 255, 255));
        ilaç.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        ilaç.setForeground(new java.awt.Color(204, 204, 255));
        ilaç.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ilaçMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ilaçMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ilaçMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilaç.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel15.setText("İlaçlar");

        javax.swing.GroupLayout ilaçLayout = new javax.swing.GroupLayout(ilaç);
        ilaç.setLayout(ilaçLayout);
        ilaçLayout.setHorizontalGroup(
            ilaçLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilaçLayout.createSequentialGroup()
                .addGroup(ilaçLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ilaçLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ilaçLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ilaçLayout.setVerticalGroup(
            ilaçLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilaçLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        hasta.setBackground(new java.awt.Color(255, 255, 255));
        hasta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        hasta.setForeground(new java.awt.Color(204, 204, 255));
        hasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hastaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hastaMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("Danışan");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasta.png"))); // NOI18N

        javax.swing.GroupLayout hastaLayout = new javax.swing.GroupLayout(hasta);
        hasta.setLayout(hastaLayout);
        hastaLayout.setHorizontalGroup(
            hastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hastaLayout.createSequentialGroup()
                .addGroup(hastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hastaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(hastaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hastaLayout.setVerticalGroup(
            hastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hastaLayout.createSequentialGroup()
                .addGroup(hastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        jPanel10.setForeground(new java.awt.Color(204, 204, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doktor4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 218, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        kapat1.setBackground(new java.awt.Color(255, 255, 255));
        kapat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        kapat1.setForeground(new java.awt.Color(204, 204, 255));
        kapat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapat1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapat1MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kapat.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel13.setText("Kapat");

        javax.swing.GroupLayout kapat1Layout = new javax.swing.GroupLayout(kapat1);
        kapat1.setLayout(kapat1Layout);
        kapat1Layout.setHorizontalGroup(
            kapat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapat1Layout.createSequentialGroup()
                .addGroup(kapat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kapat1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kapat1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kapat1Layout.setVerticalGroup(
            kapat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapat1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilaç, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faturabilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(kapat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(4034, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rapor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ilaç, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faturabilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kapat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(690, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //private void hastaMouseClicked(java.awt.event.MouseEvent evt){}
    //aşagıdaki Entered fonksşyonu ile fareyle gelğimiz oaneli renklendiriyor
    private void hastaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaMouseEntered
      hasta.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaMouseEntered

    private void raporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raporMouseEntered
    rapor.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_raporMouseEntered

    private void ilaçMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilaçMouseEntered
    ilaç.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_ilaçMouseEntered

    private void faturabilgisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturabilgisiMouseEntered
    faturabilgisi.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_faturabilgisiMouseEntered

    private void kontrolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kontrolMouseEntered
    kontrol.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_kontrolMouseEntered
// aşagıdakı MouseExited fonksiyonu fareyi çektiğimiz panel beyaz renge geri donmesı için
    private void hastaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaMouseExited
    hasta.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaMouseExited

    private void raporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raporMouseExited
    rapor.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_raporMouseExited

    private void ilaçMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilaçMouseExited
    ilaç.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_ilaçMouseExited

    private void faturabilgisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturabilgisiMouseExited
    faturabilgisi.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_faturabilgisiMouseExited

    private void kontrolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kontrolMouseExited
    kontrol.setBackground(java.awt.Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_kontrolMouseExited

    private void hastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaMouseClicked
    Hastaekranı hastalar=new Hastaekranı();
    this.setVisible(false);
    hastalar.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaMouseClicked

    private void ilaçMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilaçMouseClicked
this.setVisible(false);
new Ilacekran().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_ilaçMouseClicked

    private void kapat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapat1MouseEntered
      kapat1.setBackground(java.awt.Color.decode("#deedee"));
        // TODO add your handling code here:
    }//GEN-LAST:event_kapat1MouseEntered

    private void kapat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapat1MouseExited
     kapat1.setBackground(java.awt.Color.WHITE);   
// TODO add your handling code here:
    }//GEN-LAST:event_kapat1MouseExited

    private void kontrolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kontrolMouseClicked
this.setVisible(false);
new Kontrolekran().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_kontrolMouseClicked

    private void raporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raporMouseClicked

this.setVisible(false);
new Raporlar().setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_raporMouseClicked

    private void faturabilgisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturabilgisiMouseClicked

this.setVisible(false);
new Kazanç().setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_faturabilgisiMouseClicked

    private void kapat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapat1MouseClicked
System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_kapat1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel faturabilgisi;
    private javax.swing.JPanel hasta;
    private javax.swing.JPanel ilaç;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel kapat1;
    private javax.swing.JPanel kontrol;
    private javax.swing.JPanel rapor;
    // End of variables declaration//GEN-END:variables

   /*static class setVisible {

        public setVisible(boolean b) {
        }
    }*/
}